version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Rest.ClientRuntime
    versions:
    - 2.3.22
  - dependency-name: Microsoft.IdentityModel.Clients.ActiveDirectory
    versions:
    - 5.2.8
